### ISSUE TITLE
Game data isn't set during unit testing

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#106]
Which can cause crashes. Should probably set it to something by default? Or add something that cycles through the available options...

**Comment by auscompgeek** [comment]
I think we should definitely have a special 2018 game data test cycler thing. Would definitely be good to have full coverage of autonomous code.

**Comment by virtuald** [comment]
Working on this now.

I think it should give an empty string in addition to the valid strings, because if a user runs a robot on a practice field and runs autonomous without setting the game data, they'll get empty game data; and the robot really should be able to deal with that without crashing.

What do you think?
