### ISSUE TITLE
simulator not simulating 20 mSec DS packet arrival times

### ISSUE THREAD

**Issue by dangyogi** [robotpy/pyfrc#107]
What it does:

When I run an IterativeRobot in the simulator, it runs my periodic functions as fast as possible.

What I expect:

It would not run the periodic functions faster than every 20 mSec.

**Comment by vanjac** [comment]
I'm having this problem also.... it was working fine in an earlier version of the 2018 simulator.

**Comment by virtuald** [comment]
I will have a lot of free time in February, so I can look into it then.

**Comment by virtuald** [comment]
https://github.com/robotpy/robotpy-wpilib/pull/437 and https://github.com/robotpy/pyfrc/pull/111 fix this issue.

Update pyfrc and robotpy-wpilib and you should no longer see this issue.

**Comment by vanjac** [comment]
Thank you, it works now. It also seems to start up much faster.

**Comment by virtuald** [comment]
Blame @auscompgeek for the fixes. 👍

**Comment by auscompgeek** [comment]
Heh, I didn't realise I accidentally fixed this. I forgot this issue was even filed.
