### ISSUE TITLE
'Reset Robot' should reinitialize components

### ISSUE THREAD

**Issue by ArchdukeTim** [robotpy/pyfrc#141]
Resetting the robot only moves it back to the starting field location, but doesn't do anything to the state of the robot. 

It would be useful to have it act as if you just opened the simulator again. Reset hal and then create the robot again. 

There are also some downsides, such as just wanting to reset so the robot doesn't go off screen. To prevent this, maybe do a hard reset if the reset button is pressed again before performing another action.

**Comment by auscompgeek** [comment]
I think this is a bad idea. Although it might be a good idea to change the button label to be more descriptive.

**Comment by virtuald** [comment]
I think having a separate reset button would be useful -- but probably the best way to do so is restart the entire process.
