### ISSUE TITLE
Joysticks don't work in autonomous mode

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#143]
Required for the 2019 game.

**Comment by virtuald** [comment]
I think this is a thing to add to the per-year settings, similar to game data.

**Comment by auscompgeek** [comment]
I dunno about it being per-year. I could imagine teams wanting to use the throttle on a Logitech joystick regardless.

**Comment by virtuald** [comment]
Previous years didn't allow joystick usage in autonomous.

**Comment by auscompgeek** [comment]
Did the driver station not previously keep sending the joystick data during autonomous? I recall it still sends joystick data when disabled, at least.

**Comment by virtuald** [comment]
If I recall correctly, I think the last value was locked in and wouldn't change.
