### ISSUE TITLE
Put simulator motor outputs in a scrollbox

### ISSUE THREAD

**Issue by vanjac** [robotpy/pyfrc#150]
With too many motors the simulator window can become too big to fit on the screen.

**Comment by virtuald** [comment]
How many motors are we talking about?

**Comment by auscompgeek** [comment]
My team had 11 Talon SRXs on the robot, and a bunch of us struggled to use the whole simulator window on some of our laptops.

**Comment by vanjac** [comment]
Around 12 for us right now

**Comment by vanjac** [comment]
Lots of team members have to use their school laptops with 13 inch screens

**Comment by vanjac** [comment]
The joystick interface is also pretty tall, it might help to condense it

**Comment by auscompgeek** [comment]
Another data point: one of my students is unable to use the reset button with 8 Talon SRXs on screen.

**Comment by virtuald** [comment]
The latest release of robotpy-ctre wraps the motors into multiple columns, which should help some. We do need a better solution though.. perhaps the websim would be better?

**Comment by vanjac** [comment]
The updated version is much better. Now it's actually too wide to fit on our school laptops. I've attached a screenshot.

Something I immediately notice is that the Solenoid display could be moved below the Digital section.

![simulator screenshot](https://user-images.githubusercontent.com/8228102/52376215-5aa63580-2a16-11e9-9009-61e648f3cbab.PNG)

**Comment by virtuald** [comment]
OBE
