### ISSUE TITLE
Github Actions: Failure on Protected Branch

### ISSUE THREAD

**Issue by TheTripleV** [robotpy/pyfrc#167]
The github action to bump dependencies attempts to push changes to `master` but fails because master is a protected branch.

Potential Solutions:
1. Give github actions an administrator token
2. Make Github Actions create a PR (and maybe auto merge them)
3. Use dependabot (and maybe auto merge).

More on dependabot:
If it runs on our repos, it will monitor Pypi for updates to packages we require and (live?) create PRs for them. It pulls dependencies from:
* requirements.txt
* setup.py / .cfg
* pyproject.toml but it doesn't seem to pick up our dependencies sadly.

I'm leaning towards options 2 or 3.

**Comment by virtuald** [comment]
Made @robotpy-bot an administrator for just this repo. Seemed easiest.
