### ISSUE TITLE
deploy: deal with out of disk space conditions

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#171]
Might want to provide a 'wipe' command to delete user code from the roborio, in case they accidentally fill up their disk?

Reference: https://www.chiefdelphi.com/t/cant-deploy-python-code/380350

**Comment by benjiboy50fonz** [comment]
What are you looking for exactly? Something like a shell script? Or an actual command, and if so, where?

**Comment by virtuald** [comment]
I suspect the best way to solve the problem mentioned in that thread is to make `./robot.py undeploy` exist, which would just open an SSH connection and execute `rm -rf /home/lvuser/py`. Probably can copy a lot of pieces from the deploy command implementation.

**Comment by benjiboy50fonz** [comment]
On it. Hopefully will have it done by tonight.

**Comment by benjiboy50fonz** [comment]
Time to close?
