### ISSUE TITLE
Cannot locate physics.py

### ISSUE THREAD

**Issue by kajchang** [robotpy/pyfrc#172]
When I run the robot simulator, `pyfrc` looks for `physics.py` in the wrong place.

```
14:51:42:025 WARNING : pyfrc.physics       : Cannot enable physics support, /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/Resources/physics.py not found
```

**Comment by virtuald** [comment]
How are you executing robot.py?

**Comment by kajchang** [comment]
I'm just running `python3 robot.py sim` with the physics module in the same folder.

I'm on Mac and installed Python through Homebrew.

**Comment by virtuald** [comment]
Sorry, I missed your response! Busy busy...

Please try https://github.com/robotpy/pyfrc/pull/173 and see if that resolves your issue.

**Comment by kajchang** [comment]
Works for me. Thanks!
