### ISSUE TITLE
Timer breaks when using PIDController

### ISSUE THREAD

**Issue by sarosenb** [robotpy/pyfrc#29]
The PIDController uses a TimerTask object which also calls Timer.delay which increments our fake_time timer while running. Since it is running on its own thread, how many calls it makes is indeterminate and  if what you wanted to get done in that time is also indeterminate. I think this means that we shouldn't be doing tests on actual time or do something different if the object type is a timertask. I am not sure which action to do so wanted to have a short discussion.

**Comment by sarosenb** [comment]
Other option is that fake timer increments on a sped up real timer based on the computers timer. that would avoid any fake time issues and allow a real delay for the threads.

**Comment by virtuald** [comment]
I neglected to look at this, sorry. Did you end up finding a solution?

**Comment by sarosenb** [comment]
I gave my opinions on what to do not sure what is a better option. It maybe as simple as not increment fake_time if the object type is a timer_task, but am hesitant to do that, wanted your opinion.
