### ISSUE TITLE
Detect that the user doesn't have any tests, and default to running the builtin

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#43]
Or, perhaps tell them that they should run the builtin.

**Comment by virtuald** [comment]
Inspired by http://www.chiefdelphi.com/forums/showthread.php?p=1524487

**Comment by ArthurAllshire** [comment]
Also, it would be nice if the library could detect that you had already run the tests on a particular code base using a checksum, and then not run them again when you are deploying, or trying to run them again.

**Comment by virtuald** [comment]
@ArthurAllshire cool idea. Looks like there's a pytest plugin that might help with this: https://pytest.org/latest/cache.html

**Comment by virtuald** [comment]
I decided to not automatically run the builtin tests, as the user might have accidentally added the tests to the wrong place. Instead, I've opted to interactively ask them if they want the tests to be created, and automatically create the tests directory + pyfrc_test.py if they say yes.
