### ISSUE TITLE
Limit on axis's in sim

### ISSUE THREAD

**Issue by onenerdyguy** [robotpy/pyfrc#45]
Currently, the sim won't go above 4 axis. This makes it difficult to sim things like a tank drive using an Xbox controller, as these axis's map to 5 and up.

**Comment by virtuald** [comment]
The underlying HAL implementation supports up to 12 axis. I added the additional two axis in the pyfrc [2016.1.3](https://github.com/robotpy/pyfrc/commit/244f3dee54a508ae6f55887545c4056d31fd89ef) release.

I also added the POV, but clicking on it with a mouse is a bit messed up. I'm tired and don't care that much, so feel free to fix it and submit a patch -- code is at https://github.com/robotpy/pyfrc/blob/master/lib/pyfrc/sim/ui_widgets.py#L119. :)
