### ISSUE TITLE
Simulator issue when joystick axis is 1.0

### ISSUE THREAD

**Issue by ryannazaretian** [robotpy/pyfrc#58]
Under hal_impl\function.py, line 237:
axes.axes = [_axes_list[int(a_128)+128] for a in hal_data['joysticks'][joystickNum]['axes']]
If a is equal to 1.0, _axes_list index will go out of range (int(1.0_128)+128) equals 256, but range of _axes_list only goes up to 255.

To fix, change both 128 scalar and offset to 127.5. 
axes.axes = [_axes_list[int(a*127.5+127.5)] for a in hal_data['joysticks'][joystickNum]['axes']]

**Comment by virtuald** [comment]
I anticipate that this will disappear in the 2017 updates.

**Comment by Twinters007** [comment]
I feel like this is a recent thing? Do you know what caused it?

**Comment by virtuald** [comment]
This no longer happens in the 2017 release.
