### ISSUE TITLE
Robot tests fail with NetworkTables errors

### ISSUE THREAD

**Issue by vanjac** [robotpy/pyfrc#63]
With the latest version on pip robot tests are failing with 9 errors for me, all related to NetworkTables. [This](https://github.com/robotpy/pyfrc/commit/e21dee1dec3843c0bddc79f5742079f4f253db6a) commit should fix it, but the pip version hasn't been updated.

Mostly the errors are are:
`AttributeError: type object 'NetworkTable' has no attribute '_staticProvider'`

`RuntimeError: Network tables has already been initialized`

**Comment by virtuald** [comment]
Yeah, pyfrc 2017 hasn't been released yet, it will be released by the end of the day.

**Comment by virtuald** [comment]
If you `pip3 install -U pyfrc` it should pull down the 2017 release of RobotPy now.
