### ISSUE TITLE
Fix the CTRE CANTalon support

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#66]
Currently, the simulator crashes when you create a CANTalon device. Would be great if someone could pitch in here, I won't have time until late in the weekend. One thing that's very important is that it shouldn't crash if robotpy-ctre isn't installed.

Eventually, we need to support devices in a more general way.

**Comment by Twinters007** [comment]
Resolved with #68?

**Comment by virtuald** [comment]
At some point someone needs to actually display the thing correctly.
