### ISSUE TITLE
Position tracking Y increments positively in downward direction

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#74]
Not what I expected. Presumably because that's the drawing's coordinate system. I suppose it should be documented or changed to be 'normal'.

**Comment by auscompgeek** [comment]
Given that WPILib follows the NED axes convention, this is probably fine as long as we stick to giving users the left half of a field image.

**Comment by auscompgeek** [comment]
OBE. This was about the old pyfrc sim GUI, which we no longer have.
