### ISSUE TITLE
Add required scheduling for notifier

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#94]
SimHooks.createCondition needs to be implemented for Notifier to work properly in pyfrc's simulation mode.

**Comment by auscompgeek** [comment]
So to our surprise, Notifier (well, TimedRobot) works correctly in simulation (give or take a period or two) — try running the code in robotpy/examples#14. I think we can probably deal with the slight timing inaccuracy here.

**Comment by auscompgeek** [comment]
So the tests robotpy/robotpy-wpilib-utilities#103 timed out…

**Comment by virtuald** [comment]
Taking a look now.

**Comment by virtuald** [comment]
It also appears that TimedRobot doesn't work with physics due to this also.

**Comment by virtuald** [comment]
A workaround for this is implemented in robotpy-wpilib/35118db556292a590750a59788df6aae4b3ed326

**Comment by virtuald** [comment]
OBE
